Repository pulumi/pulumi-aws, pull requests merged in 2019-08, with the labels that each got.

#701 Add RDS T3 instance types
  CHANGELOG.md
  sdk/nodejs/rds/instanceType.ts
Labels: area/providers

#716 Upgrade to v2.25.0 of the AWS Terraform Provider
  CHANGELOG.md
  go.mod
  go.sum
  sdk/go/aws/rds/cluster.go
  sdk/nodejs/rds/cluster.ts
  sdk/python/pulumi_aws/rds/cluster.py
Labels: area/providers, kind/enhancement

#724 Add "Get Started" CTA for Pulumi AWS
  README.md
Labels: impact/no-changelog-required
