Repository pulumi/pulumi-aws, pull requests merged in 2019-05, with the labels that each got.

#551 Strict changes.
  sdk/nodejs/cloudwatch/eventRuleMixins.ts
  sdk/nodejs/dlm/policy.ts
  sdk/nodejs/dynamodb/dynamodbMixins.ts
  sdk/nodejs/kinesis/kinesisMixins.ts
  sdk/nodejs/lambda/lambdaMixins.ts
Labels: impact/no-changelog-required

#563 examples: Update serverless-raw example to nodejs 8.10
  examples/serverless-raw/index.ts
Labels: area/examples, impact/no-changelog-required

#565 Update Python SDK in Webserver example
  examples/webserver-py/requirements.txt
  resources.go
Labels: impact/no-changelog-required

#566 Re-run codegen after Python update
  sdk/python/setup.py
Labels: impact/no-changelog-required

#568 Pull in newer pulumi-terraform
  examples/examples_test.go
  go.mod
  go.sum
  sdk/go/aws/config/config.go
  sdk/nodejs/config/vars.ts
  sdk/nodejs/utilities.ts
  sdk/python/pulumi_aws/config/vars.py
  sdk/python/pulumi_aws/utilities.py
  sdk/python/setup.py
Labels: impact/no-changelog-required

#570 Hard code the regions for multiple-regions example
  examples/multiple-regions/index.ts
  examples/multiple-regions/package.json
Labels: impact/no-changelog-required

#571 Make method non-internal, it is used downstream.
  sdk/nodejs/lambda/lambdaMixins.ts
Labels: impact/no-changelog-required

#575 Upgrade to terraform-provider-aws v2.12.0
  CHANGELOG.md
  go.mod
  go.sum
  resources.go
  sdk/go/aws/directconnect/gatewayAssociation.go
  sdk/go/aws/directconnect/gatewayAssociationProposal.go
  sdk/go/aws/kinesis/stream.go
  sdk/go/aws/msk/cluster.go
  sdk/go/aws/msk/configuration.go
  sdk/go/aws/msk/getCluster.go
  sdk/go/aws/rds/instance.go
  sdk/go/aws/ssm/maintenanceWindowTarget.go
  sdk/nodejs/autoscaling/notification.ts
  sdk/nodejs/codebuild/project.ts
  sdk/nodejs/directconnect/gatewayAssociation.ts
  sdk/nodejs/directconnect/gatewayAssociationProposal.ts
  sdk/nodejs/index.ts
  sdk/nodejs/kinesis/stream.ts
  sdk/nodejs/msk/cluster.ts
  sdk/nodejs/msk/configuration.ts
  sdk/nodejs/msk/getCluster.ts
  sdk/nodejs/msk/index.ts
  sdk/nodejs/rds/instance.ts
  sdk/nodejs/ssm/maintenanceWindowTarget.ts
  sdk/nodejs/tsconfig.json
  sdk/python/pulumi_aws/__init__.py
  sdk/python/pulumi_aws/directconnect/gateway_association.py
  sdk/python/pulumi_aws/directconnect/gateway_association_proposal.py
  sdk/python/pulumi_aws/kinesis/stream.py
  sdk/python/pulumi_aws/msk/__init__.py
  sdk/python/pulumi_aws/msk/cluster.py
  sdk/python/pulumi_aws/msk/configuration.py
  sdk/python/pulumi_aws/msk/get_cluster.py
  sdk/python/pulumi_aws/rds/instance.py
  sdk/python/pulumi_aws/ssm/maintenance_window_target.py
  sdk/python/pulumi_aws/tables.py
Labels: area/providers

#576 Addition of Enums for SSM Parameter Types
  CHANGELOG.md
  examples/examples_test.go
  examples/ssmparameter/Pulumi.yaml
  examples/ssmparameter/README.md
  examples/ssmparameter/index.ts
  examples/ssmparameter/package.json
  examples/ssmparameter/tsconfig.json
  resources.go
  sdk/nodejs/ssm/index.ts
  sdk/nodejs/ssm/parameter.ts
  sdk/nodejs/ssm/parameterType.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, impact/usability
