Repository pulumi/pulumi-aws, pull requests merged in 2019-06, with the labels that each got.

#595 Adding constants for RDS Cluster EngineType and EngineMode
  CHANGELOG.md
  resources.go
  sdk/nodejs/rds/cluster.ts
  sdk/nodejs/rds/clusterInstance.ts
  sdk/nodejs/rds/engineMode.ts
  sdk/nodejs/rds/engineType.ts
  sdk/nodejs/rds/index.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, impact/usability, kind/enhancement

#596 Adding constants for EC2 Security Group Protocols
  CHANGELOG.md
  examples/webserver/index.ts
  resources.go
  sdk/nodejs/ec2/index.ts
  sdk/nodejs/ec2/protocolType.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, impact/usability, kind/enhancement

#594 Adding constants for IP AddressType and LoadBalancer type in ALB
  CHANGELOG.md
  resources.go
  sdk/nodejs/applicationloadbalancing/index.ts
  sdk/nodejs/applicationloadbalancing/ipAddressType.ts
  sdk/nodejs/applicationloadbalancing/loadBalancer.ts
  sdk/nodejs/applicationloadbalancing/loadBalancerType.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, impact/usability

#597 Adding Route53 RecordType constants
  CHANGELOG.md
  examples/examples_test.go
  examples/route53/Pulumi.yaml
  examples/route53/README.md
  examples/route53/index.ts
  examples/route53/package.json
  examples/route53/tsconfig.json
  resources.go
  sdk/nodejs/route53/index.ts
  sdk/nodejs/route53/record.ts
  sdk/nodejs/route53/recordType.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, impact/usability, kind/enhancement

#599 Use a module instead of an abstract class.
  sdk/nodejs/route53/recordType.ts
Labels: impact/no-changelog-required

#601 Adding the ability to specify PolicyDocument in aws.iam.Policy
  CHANGELOG.md
  resources.go
  sdk/nodejs/iam/policy.ts
Labels: area/providers, impact/usability

#602 Add the ability to pass a PolicyDocument to aws.s3.Bucket policy field
  CHANGELOG.md
  resources.go
  sdk/nodejs/s3/bucket.ts
Labels: area/providers, impact/usability, kind/enhancement

#607 Add helper function for typechecking.
  sdk/nodejs/lambda/lambdaMixins.ts
Labels: impact/no-changelog-required

#611 Update the available Lambda Runtimes
  CHANGELOG.md
  sdk/nodejs/lambda/runtimes.ts
Labels: area/providers, kind/enhancement

#614 Set region to something invalid to ensure all code is using providers properly.
  examples/bucket/index.ts
  examples/cloudwatch/index.ts
  examples/delete_before_create/mount_target/step1/index.ts
  examples/delete_before_create/mount_target/step1/linuxAmi.ts
  examples/delete_before_create/mount_target/step2/index.ts
  examples/delete_before_create/mount_target/step3/index.ts
  examples/examples_test.go
  examples/express/index.ts
  examples/ignoreChanges/index.ts
  examples/ignoreChanges/step1/index.ts
  examples/logGroup/index.ts
  examples/multiple-regions/index.ts
  examples/queue/index.ts
  examples/regression/217.ts
  examples/regression/250.ts
  examples/route53/index.ts
  examples/serverless-raw/index.ts
  examples/serverless/index.ts
  examples/serverless_functions/index.ts
  examples/ssmparameter/index.ts
  examples/stream/index.ts
  examples/switchrole/create-user-and-role/index.ts
  examples/switchrole/use-role/index.ts
  examples/table/index.ts
  examples/topic/index.ts
  examples/webserver-comp/linuxAmi.ts
  examples/webserver-comp/webserver.ts
  examples/webserver/index.ts
  examples/webserver/linuxAmi.ts
  examples/webserver/variants/get/index.ts
  examples/webserver/variants/get/linuxAmi.ts
  examples/webserver/variants/ssh/index.ts
  examples/webserver/variants/ssh/linuxAmi.ts
  examples/webserver/variants/ssh_description/index.ts
  examples/webserver/variants/ssh_description/linuxAmi.ts
  examples/webserver/variants/zones/index.ts
  examples/webserver/variants/zones/linuxAmi.ts
  resources.go
  sdk/nodejs/cloudwatch/logGroupMixins.ts
  sdk/nodejs/package.json
Labels: impact/no-changelog-required

#615 Fix test error
  examples/webserver/index.ts
Labels: impact/no-changelog-required

#617 Fix test
  examples/webserver/variants/get/index.ts
Labels: impact/no-changelog-required

#618 Pass along provider opts
  examples/webserver/variants/zones/index.ts
Labels: impact/no-changelog-required

#619 Fix tests
  examples/examples_test.go
  examples/webserver/variants/zones/index.ts
Labels: impact/no-changelog-required

#613 Adding constants for RDS InstanceTypes
  CHANGELOG.md
  resources.go
  sdk/nodejs/rds/clusterInstance.ts
  sdk/nodejs/rds/index.ts
  sdk/nodejs/rds/instance.ts
  sdk/nodejs/rds/instanceType.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, kind/enhancement

#620 Merge aliases, don't overwrite them.
  sdk/nodejs/cloudwatch/eventRuleMixins.ts
  sdk/nodejs/cloudwatch/logGroupMixins.ts
  sdk/nodejs/dynamodb/dynamodbMixins.ts
  sdk/nodejs/kinesis/kinesisMixins.ts
  sdk/nodejs/s3/s3Mixins.ts
  sdk/nodejs/sns/snsMixins.ts
  sdk/nodejs/sqs/sqsMixins.ts
  sdk/nodejs/utils.ts
Labels: impact/no-changelog-required

#623 Use the easier alias form.
  resources.go
  sdk/nodejs/cloudwatch/eventRuleMixins.ts
  sdk/nodejs/cloudwatch/logGroupMixins.ts
  sdk/nodejs/dynamodb/dynamodbMixins.ts
  sdk/nodejs/kinesis/kinesisMixins.ts
  sdk/nodejs/package.json
  sdk/nodejs/s3/s3Mixins.ts
  sdk/nodejs/sns/snsMixins.ts
  sdk/nodejs/sqs/sqsMixins.ts
Labels: impact/no-changelog-required

#625 Properly parent resources
  sdk/nodejs/cloudwatch/eventRuleMixins.ts
  sdk/nodejs/cloudwatch/logGroupMixins.ts
  sdk/nodejs/dynamodb/dynamodbMixins.ts
  sdk/nodejs/kinesis/kinesisMixins.ts
  sdk/nodejs/s3/s3Mixins.ts
  sdk/nodejs/sns/snsMixins.ts
  sdk/nodejs/sqs/sqsMixins.ts
Labels: impact/no-changelog-required

#622 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
Labels: area/providers

#629 Add aws.iam.PolicyDocument as AltType to ElasticSearch resources
  CHANGELOG.md
  resources.go
  sdk/nodejs/elasticsearch/domain.ts
  sdk/nodejs/elasticsearch/domainPolicy.ts
Labels: area/providers, impact/usability

#630 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required

#632 Add the ability to pass an aws.iam.PolicyDocument to ECR Repo policy
  CHANGELOG.md
  resources.go
  sdk/nodejs/ecr/repositoryPolicy.ts
Labels: area/providers, impact/usability

#612 Adding the ability to pass code directly to lambda layer_version
  CHANGELOG.md
  examples/examples_test.go
  examples/lambda-layer/.gitignore
  examples/lambda-layer/Pulumi.yaml
  examples/lambda-layer/index.ts
  examples/lambda-layer/package.json
  examples/lambda-layer/tsconfig.json
  resources.go
  sdk/go/aws/lambda/layerVersion.go
  sdk/nodejs/lambda/layerVersion.ts
  sdk/python/pulumi_aws/lambda_/layer_version.py
Labels: area/providers, kind/enhancement

#636 Upgrade to v2.17.0 of the AWS Terraform provider
  CHANGELOG.md
  go.mod
  go.sum
  resources.go
  sdk/go/aws/acm/getCertificate.go
  sdk/go/aws/appautoscaling/policy.go
  sdk/go/aws/appmesh/mesh.go
  sdk/go/aws/appsync/function.go
  sdk/go/aws/appsync/resolver.go
  sdk/go/aws/dms/endpoint.go
  sdk/go/aws/ebs/getDefaultKmsKey.go
  sdk/go/aws/ebs/getEncryptionByDefault.go
  sdk/go/aws/kinesis/stream.go
  sdk/go/aws/rds/instance.go
  sdk/go/aws/ssm/getParameter.go
  sdk/go/aws/ssm/parameter.go
  sdk/nodejs/acm/getCertificate.ts
  sdk/nodejs/appautoscaling/policy.ts
  sdk/nodejs/appmesh/mesh.ts
  sdk/nodejs/appsync/function.ts
  sdk/nodejs/appsync/index.ts
  sdk/nodejs/appsync/resolver.ts
  sdk/nodejs/config/vars.ts
  sdk/nodejs/dms/endpoint.ts
  sdk/nodejs/dms/replicationInstance.ts
  sdk/nodejs/ebs/getDefaultKmsKey.ts
  sdk/nodejs/ebs/getEncryptionByDefault.ts
  sdk/nodejs/ebs/index.ts
  sdk/nodejs/ec2/flowLog.ts
  sdk/nodejs/ec2/getCustomerGateway.ts
  sdk/nodejs/kinesis/stream.ts
  sdk/nodejs/msk/cluster.ts
  sdk/nodejs/provider.ts
  sdk/nodejs/rds/instance.ts
  sdk/nodejs/s3/bucketPublicAccessBlock.ts
  sdk/nodejs/ssm/getParameter.ts
  sdk/nodejs/ssm/parameter.ts
  sdk/nodejs/tsconfig.json
  sdk/python/pulumi_aws/acm/get_certificate.py
  sdk/python/pulumi_aws/appautoscaling/policy.py
  sdk/python/pulumi_aws/appmesh/mesh.py
  sdk/python/pulumi_aws/appsync/__init__.py
  sdk/python/pulumi_aws/appsync/function.py
  sdk/python/pulumi_aws/appsync/resolver.py
  sdk/python/pulumi_aws/dms/endpoint.py
  sdk/python/pulumi_aws/ebs/__init__.py
  sdk/python/pulumi_aws/ebs/get_default_kms_key.py
  sdk/python/pulumi_aws/ebs/get_encryption_by_default.py
  sdk/python/pulumi_aws/kinesis/stream.py
  sdk/python/pulumi_aws/rds/instance.py
  sdk/python/pulumi_aws/ssm/get_parameter.py
  sdk/python/pulumi_aws/ssm/parameter.py
  sdk/python/pulumi_aws/tables.py
Labels: area/providers, kind/enhancement
