Repository pulumi/pulumi-aws, pull requests merged in 2019-07, with the labels that each got.

#643 Change Route53 Record Type to have AltType of RecordType
  CHANGELOG.md
  resources.go
  sdk/nodejs/route53/record.ts
Labels: area/providers, kind/bug

#645 Upgrade to v2.18.0 of the AWS Terraform Provider
  CHANGELOG.md
  go.mod
  go.sum
  resources.go
  sdk/go/aws/appmesh/route.go
  sdk/go/aws/appmesh/virtualNode.go
  sdk/go/aws/appsync/resolver.go
  sdk/go/aws/codecommit/repository.go
  sdk/go/aws/ec2transitgateway/route.go
  sdk/go/aws/emr/cluster.go
  sdk/go/aws/lambda/getInvocation.go
  sdk/go/aws/rds/globalCluster.go
  sdk/go/aws/rds/instance.go
  sdk/go/aws/servicequotas/getService.go
  sdk/go/aws/servicequotas/getServiceQuota.go
  sdk/go/aws/ssm/maintenanceWindowTarget.go
  sdk/nodejs/apigateway/integration.ts
  sdk/nodejs/apigateway/integrationResponse.ts
  sdk/nodejs/apigateway/methodResponse.ts
  sdk/nodejs/applicationloadbalancing/listenerRule.ts
  sdk/nodejs/appmesh/route.ts
  sdk/nodejs/appmesh/virtualNode.ts
  sdk/nodejs/appsync/resolver.ts
  sdk/nodejs/cfg/rule.ts
  sdk/nodejs/codecommit/repository.ts
  sdk/nodejs/ebs/volume.ts
  sdk/nodejs/ec2transitgateway/route.ts
  sdk/nodejs/elasticloadbalancingv2/listenerRule.ts
  sdk/nodejs/emr/cluster.ts
  sdk/nodejs/index.ts
  sdk/nodejs/lambda/getInvocation.ts
  sdk/nodejs/rds/globalCluster.ts
  sdk/nodejs/rds/instance.ts
  sdk/nodejs/servicequotas/getService.ts
  sdk/nodejs/servicequotas/getServiceQuota.ts
  sdk/nodejs/servicequotas/index.ts
  sdk/nodejs/ssm/maintenanceWindowTarget.ts
  sdk/nodejs/tsconfig.json
  sdk/python/pulumi_aws/__init__.py
  sdk/python/pulumi_aws/appmesh/route.py
  sdk/python/pulumi_aws/appmesh/virtual_node.py
  sdk/python/pulumi_aws/appsync/resolver.py
  sdk/python/pulumi_aws/codecommit/repository.py
  sdk/python/pulumi_aws/ec2transitgateway/route.py
  sdk/python/pulumi_aws/emr/cluster.py
  sdk/python/pulumi_aws/lambda_/get_invocation.py
  sdk/python/pulumi_aws/rds/global_cluster.py
  sdk/python/pulumi_aws/rds/instance.py
  sdk/python/pulumi_aws/servicequotas/__init__.py
  sdk/python/pulumi_aws/servicequotas/get_service.py
  sdk/python/pulumi_aws/servicequotas/get_service_quota.py
  sdk/python/pulumi_aws/ssm/maintenance_window_target.py
Labels: area/providers, kind/enhancement

#640 Update pulumi-terraform to a9a9ca8157
  go.mod
  go.sum
Labels: area/providers

#638 Add Lambda runtime constants for go
  CHANGELOG.md
  sdk/go/aws/lambda/runtime.go
Labels: area/providers, impact/usability, kind/enhancement

#653 Adding module containing constants for RDS DB Instance StorageType
  CHANGELOG.md
  resources.go
  sdk/nodejs/rds/index.ts
  sdk/nodejs/rds/instance.ts
  sdk/nodejs/rds/storageType.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, impact/usability, kind/enhancement

#652 Update package level README.md's
  sdk/go/aws/aws.go
  sdk/nodejs/README.md
  sdk/python/pulumi_aws/README.md
Labels: impact/no-changelog-required

#654 Produce better error if a table doesn't support onEvent callback.
  sdk/nodejs/dynamodb/dynamodbMixins.ts
Labels: impact/no-changelog-required

#656 Update pulumi-terraform to 08d502e9b4
  go.mod
  go.sum
Labels: area/providers

#660 Adding an ECR Lifecycle Document Type
  CHANGELOG.md
  examples/ecr/Pulumi.yaml
  examples/ecr/README.md
  examples/ecr/index.ts
  examples/ecr/package.json
  examples/ecr/tsconfig.json
  examples/examples_test.go
  resources.go
  sdk/nodejs/ecr/index.ts
  sdk/nodejs/ecr/lifecyclePolicy.ts
  sdk/nodejs/ecr/lifecyclePolicyDocument.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers, impact/usability, kind/enhancement

#664 Use sync method
  examples/multiple-regions/index.ts
Labels: impact/no-changelog-required

#670 Add simple python test
  examples/alb-legacy-py/.gitignore
  examples/alb-legacy-py/Pipfile
  examples/alb-legacy-py/Pulumi.yaml
  examples/alb-legacy-py/__main__.py
  examples/alb-legacy-py/requirements.txt
  examples/examples_test.go
Labels: impact/no-changelog-required

#665 Change iam PolicyDocument to accept Input parameters
  CHANGELOG.md
  sdk/nodejs/iam/documents.ts
Labels: area/providers, impact/usability, kind/enhancement

#681 Add support for new Middle East Region in location constants
  sdk/nodejs/region.ts
Labels: impact/no-changelog-required

#659 Add support for RepositoryCredentials in ecs ContainerDefinition
  CHANGELOG.md
  sdk/nodejs/ecs/container.ts
Labels: area/providers, kind/enhancement
